### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by CWSwastik** [CWSwastik/bitsmegle#1]
# TODO
- [x] Refactor 
- [ ] Fix types

# Security
- [x] CSRF 
- [x] Remove firebase
- [x] Send Access tokens in cookies

# Functionality
- [x] Disable buttons
- [x] Add database

# UI
- [x] UI Redesign
- [x] Fix video size
- [ ] Pick Font
- [ ] Color Scheme
- [ ] Logo
- [ ] Profile Page
- [x] Mobile view on landscape
- [ ] Tap to toggle nameplate
- [ ] Fix temp solution of using loader.png for pausing animation
- [ ] Add timer for rating
- [ ] Auth in rating
- [ ] Badges (Database)

# New features
- [ ] Chat window
